Openblas: Add x86_64-windows as new plattform
I'm currently trying to CrossCompile numpy for Windows:

Before this patch

```
env NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1 nix-build -A pkgs.pkgsCross.mingwW64.python3Packages.numpy --show-trace
```
Failes with `unsupported system: x64_64-linux error when executing` (and
openblas was mentioned in the trace).

TARGET was set to my CPU architecture based [1]. However to my
understanding it should work for other architecture as well because
DYNAMIC_ARCH is set to true.

After this change is applied the above pkgsCross call failes with:
```
$ env NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1 nix-build -A pkgs.pkgsCross.mingwW64.python3Packages.numpy --show-trace

error: builder for '/nix/store/88zs65jliz05rwdn29xdrmmswsx2raj6-bash-x86_64-w64-mingw32-5.2p26.drv' failed with exit code 2;
       last 10 log lines:
       > make: *** [Makefile:105: assoc.o] Error 1
       > make: *** [Makefile:105: list.o] Error 1
       > make: *** [Makefile:105: findcmd.o] Error 1
       > make: *** [Makefile:105: hashlib.o] Error 1
       > make: *** [Makefile:105: array.o] Error 1
       > make[1]: *** [Makefile:77: man2html.o] Error 1
       > make[1]: Leaving directory '/build/bash-5.2/support'
       > make: *** [Makefile:768: support/man2html.exe] Error 1
       > gcc  -g -DCROSS_COMPILING -o mkbuiltins.exe mkbuiltins.o
       > make[1]: Leaving directory '/build/bash-5.2/builtins'
       For full logs, run 'nix-store -l /nix/store/88zs65jliz05rwdn29xdrmmswsx2raj6-bash-x86_64-w64-mingw32-5.2p26.drv'.
error: 1 dependencies of derivation '/nix/store/6cs6pxmzym2w0sw485jx90xj925bzh35-make-shell-wrapper-hook.drv' failed to build
building '/nix/store/w36is5wbpq434zqzhxminsh08bqxpkfw-bzip2-x86_64-w64-mingw32-1.0.8.drv'...
error: 1 dependencies of derivation '/nix/store/857gsrqlk4hvf6lnhin2mkrk63gfx9cx-wrap-python-hook.drv' failed to build
error: 1 dependencies of derivation '/nix/store/7jvf5icaqh2lgn56b4c3jhfjl2sd2xn2-python3.11-numpy-1.26.4-x86_64-w64-mingw32.drv' failed to build
```

Which is the same as when running
```
$ env NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1 nix-build -A pkgs.pkgsCross.mingwW64.bash --show-trace
```
There is already a known issue for that (just google
pkgs.pkgsCross.mingwW64.bash)

[1] https://github.com/OpenMathLib/OpenBLAS/blob/develop/TargetList.txt